# ==============================================================================
# VERITAS Application Secrets Configuration
#
# !! CRITICAL SECURITY NOTICE !!
# This file contains sensitive credentials and configuration.
# DO NOT commit this file to any public or private Git repository.
# Use environment variables or a dedicated secret management service for production.
# For Streamlit Community Cloud, these values should be entered in the web UI.
# ==============================================================================

# ------------------------------------------------------------------------------
# Production Database Connection (e.g., Snowflake)
# These values will be used by the ProdDataRepository.
# ------------------------------------------------------------------------------
[database]
user = "your_service_account_user"
password = "your_service_account_password"
account = "your_snowflake_account_identifier" # e.g., xy12345.us-east-1
warehouse = "PROD_DTE_WH"
database = "PROD_DATA_WAREHOUSE"
schema = "VERITAS_REPORTING"
role = "VERITAS_APP_ROLE"

# ------------------------------------------------------------------------------
# Web Analytics (e.g., Google Analytics 4)
# Used for application usage monitoring.
# ------------------------------------------------------------------------------
[analytics]
ga4_script = '''
<!-- PASTE YOUR GOOGLE ANALYTICS (GTAG.JS) SCRIPT HERE -->
<!-- Example Placeholder -->
<!-- Google tag (gtag.js) -->
<script async src="https://www.googletagmanager.com/gtag/js?id=G-XXXXXXXXXX"></script>
<script>
  window.dataLayer = window.dataLayer || [];
  function gtag(){dataLayer.push(arguments);}
  gtag('js', new Date());

  gtag('config', 'G-XXXXXXXXXX');
</script>
'''

# ------------------------------------------------------------------------------
# Other API Keys (Example)
# Placeholder for future integrations, e.g., a ticketing system like JIRA.
# ------------------------------------------------------------------------------
[jira]
api_token = "your_jira_api_token"
server_url = "https://your-company.atlassian.net"
